version: '2'

tasks:
  main-task:
    cmds:
      - task: build-nvme-libs
      - task: unit-tests
      - task: build-nvme
      - task: build-spdk

  build-nvme-libs:
    dir: nvme
    cmds:
      - rm -f nvme_discover.o nvme_discover.so
      - gcc -c -fpic -Iinclude src/nvme_discover.c -lspdk
      - gcc -shared -o libnvme_discover.so nvme_discover.o

  unit-tests:
    dir: nvme
    cmds:
      - go test

  build-nvme:
    dir: nvme
    deps: [lint]
    cmds:
      - go build -v -i nvme.go

  build-spdk:
    dir: spdk
    deps: [lint]
    cmds:
      - go build -v -i spdk.go

  lint:
    cmds:
      - gofmt -l -s -w . && go tool vet -all . && golint
