version: '2'

tasks:
  main-task:
    cmds:
      - task: build-c-libs
      - task: build-go

  build-c-libs:
    dir: spdk
    cmds:
      - rm -f nvme_discover.o nvme_discover.so
      - gcc -I/home/tanabarr/projects/daos_m/install/include -c -fpic -Iinclude src/nvme_discover.c -lspdk
      - gcc -shared -o libnvme_discover.so nvme_discover.o
 
  build-go:
    dir: spdk
    deps: [lint]
    cmds:
      - go build -v -i spdk.go

  lint:
    cmds:
      - gofmt -l -s -w . && go tool vet -all . && golint
